// Publishes straight to the user's own repo using their fine-grained token (Contents: read & write).
// Everything lands in a single commit via the Git Data API.

const API = 'https://api.github.com'

export class GitHub {
  constructor(token) {
    this.token = token
  }

  async req(method, path, body) {
    const res = await fetch(`${API}${path}`, {
      method,
      credentials: 'omit',
      referrerPolicy: 'no-referrer',
      headers: {
        Accept: 'application/vnd.github+json',
        Authorization: `Bearer ${this.token}`,
        'X-GitHub-Api-Version': '2022-11-28',
        ...(body ? { 'Content-Type': 'application/json' } : {}),
      },
      body: body ? JSON.stringify(body) : undefined,
    })
    if (!res.ok) {
      let msg = `${res.status} ${res.statusText}`
      try {
        msg = (await res.json()).message ?? msg
      } catch {}
      const err = new Error(`GitHub: ${msg}`)
      err.status = res.status
      throw err
    }
    return res.status === 204 ? null : res.json()
  }
}

const b64FromBlob = async (blob) => {
  const bytes = new Uint8Array(await blob.arrayBuffer())
  let bin = ''
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  return btoa(bin)
}

const b64FromText = (text) => b64FromBlob(new Blob([text]))

const enc = (path) => path.split('/').map(encodeURIComponent).join('/')

export const rawUrl = (owner, repo, ref, path) =>
  `https://raw.githubusercontent.com/${owner}/${repo}/${ref}/${enc(path)}`

export async function currentUser(token) {
  const u = await new GitHub(token).req('GET', '/user')
  return { login: u.login, avatar: u.avatar_url }
}

/** Make sure a public repo exists (creating it if needed). Returns { created, defaultBranch }. */
export async function ensureRepo({ owner, repo }, token, log = () => {}) {
  const gh = new GitHub(token)
  try {
    const info = await gh.req('GET', `/repos/${owner}/${repo}`)
    return { created: false, defaultBranch: info.default_branch, private: info.private }
  } catch (e) {
    if (e.status !== 404) throw e
  }
  const me = await currentUser(token)
  if (me.login.toLowerCase() !== owner.toLowerCase()) throw new Error(`Repository ${owner}/${repo} not found.`)
  log(`Creating public repo ${owner}/${repo}…`)
  let info
  try {
    info = await gh.req('POST', '/user/repos', {
    name: repo,
    description: 'Fusion collection covers (made with Covers)',
    private: false,
    auto_init: true,
    has_issues: false,
    has_wiki: false,
    has_projects: false,
    })
  } catch (e) {
    // Fine-grained tokens limited to selected repos can't create repos (or even see new ones).
    if (e.status !== 403 && e.status !== 422) throw e
    const err = new Error(`Your token can't create or access ${owner}/${repo}.`)
    err.needsRepo = { owner, repo }
    throw err
  }
  return { created: true, defaultBranch: info.default_branch, private: false }
}

export async function checkRepo({ owner, repo }, token) {
  const gh = new GitHub(token)
  const info = await gh.req('GET', `/repos/${owner}/${repo}`)
  return { private: info.private, defaultBranch: info.default_branch, canPush: info.permissions?.push !== false }
}

/**
 * files: [{ path, blob }] images; buildConfig(urlFor) -> config object once image URLs are known.
 */
export async function publish({ owner, repo, branch, dir }, token, images, buildConfig, log = () => {}) {
  const gh = new GitHub(token)
  const R = `/repos/${owner}/${repo}`
  const base = dir.replace(/^\/+|\/+$/g, '')
  const join = (p) => (base ? `${base}/${p}` : p)

  log('Checking repository…')
  const info = await gh.req('GET', R)
  if (info.private) log('⚠ Repo is private — Fusion cannot read raw files from private repos.')

  let headSha
  try {
    headSha = (await gh.req('GET', `${R}/git/ref/heads/${enc(branch)}`)).object.sha
  } catch (e) {
    if (e.status !== 404 && e.status !== 409) throw e
    log(`Branch “${branch}” missing or repo empty — creating it…`)
    await gh.req('PUT', `${R}/contents/${enc(join('.keep'))}`, {
      message: 'Initialize Fusion covers',
      content: btoa('Generated by Covers\n'),
      branch,
    })
    headSha = (await gh.req('GET', `${R}/git/ref/heads/${enc(branch)}`)).object.sha
  }
  const headCommit = await gh.req('GET', `${R}/git/commits/${headSha}`)

  const tree = []
  const wanted = new Set()
  for (const [i, img] of images.entries()) {
    log(`Uploading cover ${i + 1}/${images.length}…`)
    const blob = await gh.req('POST', `${R}/git/blobs`, { content: await b64FromBlob(img.blob), encoding: 'base64' })
    const path = join(`covers/${img.name}`)
    wanted.add(path)
    tree.push({ path, mode: '100644', type: 'blob', sha: blob.sha })
    img.sha = blob.sha
  }

  // Remove covers from previous publishes that no longer exist.
  const existing = await gh.req('GET', `${R}/git/trees/${headCommit.tree.sha}?recursive=1`)
  for (const entry of existing.tree) {
    if (entry.type === 'blob' && entry.path.startsWith(join('covers/')) && !wanted.has(entry.path)) {
      tree.push({ path: entry.path, mode: '100644', type: 'blob', sha: null })
    }
  }

  // Blob SHA in the query string busts Fusion's/CDN image cache only when the picture actually changed.
  const urlFor = Object.fromEntries(
    images.map((img) => [img.id, `${rawUrl(owner, repo, branch, join(`covers/${img.name}`))}?v=${img.sha.slice(0, 10)}`]),
  )
  const config = buildConfig(urlFor)
  log('Writing config.json…')
  const cfgBlob = await gh.req('POST', `${R}/git/blobs`, {
    content: await b64FromText(JSON.stringify(config, null, 2)),
    encoding: 'base64',
  })
  tree.push({ path: join('config.json'), mode: '100644', type: 'blob', sha: cfgBlob.sha })

  log('Committing…')
  const newTree = await gh.req('POST', `${R}/git/trees`, { base_tree: headCommit.tree.sha, tree })
  if (newTree.sha === headCommit.tree.sha) {
    log('Nothing changed since last publish.')
  } else {
    const commit = await gh.req('POST', `${R}/git/commits`, {
      message: `Update Fusion collections (${images.length} covers)`,
      tree: newTree.sha,
      parents: [headSha],
    })
    await gh.req('PATCH', `${R}/git/refs/heads/${enc(branch)}`, { sha: commit.sha })
  }

  log('Done ✓')
  return { url: rawUrl(owner, repo, branch, join('config.json')), urlFor }
}
